// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface Event {
  id: number /* int */;
  title: string;
  description: string;
  imageUrl: string;
  date: Date ;
  createdAt: Date ;
}
export interface CreateEventRequest {
  title: string;
  description: string;
  imageUrl: string;
  date: Date ;
}
export interface UpdateEventRequest {
  id: number /* int */;
  title: string;
  description: string;
  imageUrl: string;
  date: Date ;
}
/**
 * users
 */
export interface User {
  id: number /* int */;
  firstName: string;
  lastName: string;
  email: string;
  createdAt: Date ;
}
export interface RegisterRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
}
export interface LoginRequest {
  email: string;
  password: string;
}
